name: Build binaries
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name
        required: true
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Sync repository
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          brew: postgresql@14 protobuf
          apt: lld postgresql protobuf-compiler
      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Binary name.
          bin: influxdb_iox
          # On which platform to distribute the `.tar.gz` file.
          tar: unix
          # GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fully-formed tag ref.
          ref: refs/tags/${{ inputs.tag }}
          # Algorithm to be used for checksum.
          checksum: sha256
