name: Build executables

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: ConorMacBride/install-package@v1
        with:
          brew: postgresql@14 protobuf
      - name: Build
        run: cargo build --release --verbose
